python predict_resnet_smallest.py "$@"
python predict_inception_520.py "$@"
python predict_inception_v3_520.py "$@"
python predict_linknet.py "$@"
python predict_linknet_520.py "$@"
python predict_vgg.py "$@"
